language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: MvYlS7+flQHX0tEWkQolWKaTv7Jp+xWLreBPH7TtqxgCMrsrOS0IUSrLNAPKYmId5nKdTg7z1E/v0BKgg99u56A2mmiQvRvuWUa+lRxKf2OfzwzQ2bEfxNSU7VhvbD7/J3iEf1rGifTw19zCuVWFbqvuMtOSUWU1N6aaKh28ORG5c/ZkZsrSvgG38eTqIs5jfMSiC/r+xvN95I2xGoLbpmivb4uM2KiQUd71H1wR3N8nyixAJNAfhG8KBQbPxqCT0J3YWl6gLWFLfE0l3spYgP9Z2v94IQXyB0Z5xqZFDnuWuguSwC19HT5aQz7Uz/HUR4SEawGA9Qs1hQNK2k22hR1x4GeeiT5A3D0W+ttivt9OV/P9Ly9MzduHzuEOD5ZtaZPbNmicNSc6ayCaevlMk9SFDUi3jvRaDr3vz1RNcT0aIxFBm/BaN8sUSPBYyX5AvjsXmwwLMeVNAQXnpA19Ag9tefdcUh6dGcgQ2+DojY+x5eXOQjnC8kRBZEmyuThkGcnyd9sFH83RulW8K0zxwQt1jVOLzF4L13Q/9OE6fEs6EV48EHtiGbDWL5RE/G7u/cVrqvgm09RS7PU8q/ApcAVuW9z4CSuH9N7kuXlLiGPtRQyEifLDw19LG+DdMNGfFQGqSwvAbPnH/ZN2eBhez9KIdd6vyUm0fn/Up0qft/A=
  app: shrouded-hamlet-23160
  on:
    repo: Vlacross/Re-Cap-Server
