language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: LzfVjkknZs3n3twqm61uEC5nmC3terpfZf9Po4LslyP2duZo92nzvw5Tup8NwIQt4LZ2mON+0K41CD/xy61f/wQj6ZxC+bdaFnP2s8IuBI54LpnqDeJSkyzXcD2TivbbtJk2dwtCf4h45Op5125G3cyqibZHrxOIhD5DAKaEhzej0rJ3Hh1ZWGsa6KXT/dl+Fxtt1dds8a559cR+hLOIf1kjx3xdtLKn9eNTKmTt+oVET2Ty0jj0iEMxT4vmfSFJ7+IjwrhSush0/fjrbPCozG994O0QC/agXmct2KQGZSyB1s/+YT5WDNgJbDSAR3xnIAdLcGyMGRlDKG6G07NJuoiP/JN/mMmKyEvJiX8QZXmLeysdmnc4NdE6C/E9bD0Eju03QQewmi0tUSYjsP3esP6buwf9TTfle4Pn/VF/RHSX9qUg6dG61glE0abLmA3zT51gUaOLWtSU9v1gxRtWGXaGwSeMiuf/435MZ1Yw8g3pfggiEMnDZ07mTtpLjhgH5a1JqKzfAtUiD4S0ErPakYZsUoTFfmCVqu+iVbEKLhLNrpnCa/oaItkCx9r5xGFqSc0U4LpLZasxSPcKX2q47wxVx9tvJGoXSygperHhQAxRHCDfxZEPn08i0YMkCm7fC5Zss7siHwGJJ8k81mKOPFo8ORUlp3kybs8oEnceoy4=
  app: shrouded-hamlet-23160
  on:
    repo: Vlacross/Re-Cap-Server
