language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: AyBGcmL/OWzzpvT1sF9SHUrdKsAuiFeG01mu3EfDaay1zd2XL9ExiXnpQNDM0R0eUxnn3WI45HyiEKB5qnCdTecayIIDEymc2hDV458IqyCNKKCIT/JLIwPhOTxRQVQoNqOqtBkwkENH/h/RuQ9WKFxlbQR+HaL17vQFqQ0/gGaj+KjhRkvpMMeQGX8CedfxaJRdijlKW9wWJ/YIlpOr9aXGCx33bMLJIQhcwuh1XbVuilCZzXJG/NuF2nhPCeN17VlKslTQwvBk1fpeiYI0Rc7dMfqzJ+jy9SFfIm1ZGmui0AG+n/zOlOrQyLac83dVPHLokqoPFkGryAtOwXHqmzy6EukhigTi2OCpEB/6nwwI5Kiksq7dKTT/2QYTG27A/3NctPFk70sz1O25GHXfP9T4rBKNH3gkFxohyOs4Uail7MbNtjGbrqUwLljD6LeHRGsF1zwNgN4/Q8u/GDWxxVlcNX3B+axqj0etI8cm7UqYFZDutDfktmMjGagVEKLu2FE3Ugcmop9CfzVt5QPp6K5Lu+FIcY5ktIafEjN6COnmjY5Hg+Njy9FlBdbBQ5askowZmr5mv9PKj+dblT3b9uGFNB6xsutFfn0pYs8+mCegNwwuVQ7iDrnC1qeSoe+AfkQm7RQfQLKrNfFFCNiy7rXDpaeJcazMADxqNVBahhQ=
  app: shrouded-hamlet-23160
  on:
    repo: Vlacross/Re-Cap-Server
